In [1]:
import torch
import numpy as np

# code를 보면서 많이 볼 수 있는 어색한 문법?들에 대해 모아둡니다!  

Torch나 Numpy에서 [None] [None,None] 이런 문법을 굉장히 많이 볼 수 있습니다  
처음에 보면 인덱스을 넣을 자리에 None을 넣는게 도대체 뭐하는건지 혼란스럽습니다  
None을 넣는건 Torch에서 unsqueeze() 함수처럼 차원을 하나 늘려준다고 생각하면 됩니다

In [6]:
print("---Tensor---")
f1 = torch.ones((3, 8, 8))
f2 = f1[None]
f3 = f1[None, None]
f4 = f1[:,None]
print(f"f1 shape : {f1.shape}\nf2 shape : {f2.shape}\nf3 shape : {f3.shape},\nf4 shape : {f4.shape}")

---Tensor---
f1 shape : torch.Size([3, 8, 8])
f2 shape : torch.Size([1, 3, 8, 8])
f3 shape : torch.Size([1, 1, 3, 8, 8]), f4 shape : torch.Size([3, 1, 8, 8])


In [7]:
print("---Numpy---")
f1 = np.ones((3, 8, 8))
f2 = f1[None]
f3 = f1[:, :, :, None, None]
print(f"f1 shape : {f1.shape}\nf2 shape : {f2.shape}\nf3 shape : {f3.shape}")

---Numpy---
f1 shape : (3, 8, 8)
f2 shape : (1, 3, 8, 8)
f3 shape : (3, 8, 8, 1, 1)


위과 같이 차원을 늘리는 경우가 많습니다!  

## 인덱스에 ... 을 쓰는 경우  
code 중에 [ ] 안에 ... 가 들어가 있는 경우가 많습니다.  
간단히 말하면 [:] 에서 : 를 여러번 쓰기 귀찮을 경우 ... 를 적는 경우입니다.  
4차원 tensor에서 B x C x H x W 에서 W만 건드리고 싶은경우  
tensor[:, :, :, 5] == tensor[..., 5] 입니다.  
tensor[:, ... , 5] 어디든지 들어가서 : 여러개 쓰는 것 대신 쓸 수 있습니다.  

In [2]:
f1 = torch.zeros((1, 1, 5, 5))
print(f1)
f1[:, :, :, 2] = 1
print(f1)
f2 = f1[:, :, :, 2] #차원이 명확함
f3 = f1[..., 2] #직관적이진 않음 .. 근데 많이들 씀 ..

print(f2, f3)

tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])
tensor([[[[0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.]]]])
tensor([[[1., 1., 1., 1., 1.]]]) tensor([[[1., 1., 1., 1., 1.]]])
